### PR TITLE
BLoC & async & stream & http package

### PR DESCRIPTION
**Pull request by user-nazar**
**This work is an informational application related to important news from various industries and activities in the world**.

* Screenshots:

image

**Categories & topics**:
   * tech;
   * sport;
   * science;
   * health;
   * arts;
   * and others (depicted on this application as a list).
 
image

**This is an expert account**.
   * information about him;
   * number of posts read;
   * profile rating.

image
image

### CODE REVIEW

**Review by igor-leshkevych — COMMENTED** [review]
@nazartsiupryk impressive work. 
A couple of things I'd improve:
1. Using StatelessWidget instead of StatelessWidget where you don't need state (a good indicator is that you don't call `setState` there)
2. In this lab we're making a real app, not prototype, so I suggest removing all elements that are only simulating UI (for example some of your toggles at profile page). The idea is - If I see something in the app, it means that it must work and do something, if it doesnt - just get rid of it.

Do all that and you'l get maximum score

**Comment by user-nazar** [comment]
> @nazartsiupryk impressive work. A couple of things I'd improve:
> 
> 1. Using StatelessWidget instead of StatelessWidget where you don't need state (a good indicator is that you don't call `setState` there)
> 2. In this lab we're making a real app, not prototype, so I suggest removing all elements that are only simulating UI (for example some of your toggles at profile page). The idea is - If I see something in the app, it means that it must work and do something, if it doesnt - just get rid of it.
> 
> Do all that and you'l get maximum score

I do not agree with the first point.

**Comment by igor-leshkevych** [comment]
@nazartsiupryk you can leave it then, but your score is 18/20 in this case (the second issue is fixed in another PR as I can see)

**Comment by user-nazar** [comment]
> @nazartsiupryk you can leave it then, but your score is 18/20 in this case (the second issue is fixed in another PR as I can see)

**Comment by user-nazar** [comment]
> @nazartsiupryk you can leave it then, but your score is 18/20 in this case (the second issue is fixed in another PR as I can see)

I will correct this point

**Pull request closed without merging**
